from datetime import datetime, timedelta, timezone

NOW = datetime.now(timezone.utc)

DEMO_ITEMS = [
    {
        "platform": "News",
        "title": "Indian shares face pressure as higher crude and Treasury yields weigh",
        "text": "Indian equities are under pressure as crude oil rises and global yields remain elevated. Investors are watching inflation, the rupee and foreign flows.",
        "url": "https://www.reuters.com/world/india/indian-shares-set-muted-start-higher-oil-prices-treasury-yields-weigh-2026-08-19/",
        "published": NOW - timedelta(hours=2),
        "engagement": 920,
        "velocity": 88,
        "topic_hint": "crude oil and Indian equities",
    },
    {
        "platform": "News",
        "title": "RBI intervention keeps the rupee steadier amid oil pressure",
        "text": "Traders report continued RBI intervention as crude prices and global yields pressure the rupee.",
        "url": "https://www.reuters.com/world/india/indian-central-bank-likely-intervenes-shield-rupee-oil-strain-traders-say-2026-08-19/",
        "published": NOW - timedelta(hours=5),
        "engagement": 760,
        "velocity": 81,
        "topic_hint": "rupee and RBI intervention",
    },
    {
        "platform": "News",
        "title": "Mutual fund investors continue to debate allocation amid market volatility",
        "text": "Retail investors are weighing SIP discipline, balanced advantage funds and value strategies as market volatility persists.",
        "url": "https://m.economictimes.com/mf/analysis/best-balanced-advantage-funds-or-dynamic-asset-allocation-funds-to-invest-in-august-2026/articleshow/133336968.cms",
        "published": NOW - timedelta(hours=10),
        "engagement": 680,
        "velocity": 69,
        "topic_hint": "mutual fund allocation",
    },
    {
        "platform": "News",
        "title": "Value investing gains attention as growth stocks lag",
        "text": "Recent commentary highlights renewed interest in value-oriented strategies.",
        "url": "https://m.economictimes.com/mf/analysis/best-value-funds-to-invest-in-august-2026/articleshow/133228579.cms",
        "published": NOW - timedelta(days=4),
        "engagement": 540,
        "velocity": 55,
        "topic_hint": "value versus growth",
    },
    {
        "platform": "Reddit",
        "title": "Investors discuss whether market volatility should change SIP behaviour",
        "text": "A recurring investor question is whether to stop, reduce or continue SIPs during a drawdown.",
        "url": "https://www.reddit.com/r/MutualfundsIndia/",
        "published": NOW - timedelta(days=2),
        "engagement": 510,
        "velocity": 77,
        "topic_hint": "SIP behaviour during volatility",
    },
    {
        "platform": "Reddit",
        "title": "Discussion: how should investors think about a weaker rupee?",
        "text": "Investors are debating the impact of currency depreciation on international diversification and domestic assets.",
        "url": "https://www.reddit.com/r/IndiaInvestments/",
        "published": NOW - timedelta(days=1),
        "engagement": 390,
        "velocity": 73,
        "topic_hint": "rupee and global diversification",
    },
    {
        "platform": "X",
        "title": "Finance creators debate whether crude above $90 changes India's market outlook",
        "text": "Posts are connecting oil prices with inflation, the rupee, corporate margins and equity valuations.",
        "url": "https://x.com/search?q=crude%20oil%20India%20stocks",
        "published": NOW - timedelta(hours=8),
        "engagement": 1380,
        "velocity": 94,
        "topic_hint": "crude oil and Indian equities",
    },
    {
        "platform": "X",
        "title": "Investors debate whether the RBI can keep the rupee stable indefinitely",
        "text": "Discussion centres on intervention, reserves, oil imports and the trade-off between stability and fundamentals.",
        "url": "https://x.com/search?q=RBI%20rupee",
        "published": NOW - timedelta(hours=14),
        "engagement": 980,
        "velocity": 87,
        "topic_hint": "rupee and RBI intervention",
    },
    {
        "platform": "X",
        "title": "Small and mid-cap valuation debate resurfaces",
        "text": "Investors and market commentators are debating whether current valuations justify continued allocation to smaller companies.",
        "url": "https://x.com/search?q=small%20cap%20India%20valuations",
        "published": NOW - timedelta(days=3),
        "engagement": 840,
        "velocity": 71,
        "topic_hint": "small and mid-cap valuations",
    },
    {
        "platform": "Google Trends",
        "title": "Search interest around gold and silver remains elevated",
        "text": "Precious metals remain prominent in investor search behaviour amid geopolitical and inflation uncertainty.",
        "url": "https://trends.google.com/trending/?geo=IN",
        "published": NOW - timedelta(days=1),
        "engagement": 620,
        "velocity": 75,
        "topic_hint": "gold and silver allocation",
    },
]

def get_items():
    return DEMO_ITEMS
